// Generated by unRap v1.06 by Kegetys

class cfgVehicles {
	class Helicopter;	// External class reference
	
	class pragaCopter_green : Helicopter {
		scope = public;
		canfloat = true;
		icon = "\rth_copter\ico_map\copter_map_ca.paa";
		picture = "\rth_copter\ico\copter_ico_ca.paa";
		model = "\rth_copter\copter.p3d";
		faction = "rth_copter_class";
		displayName = "Praga copter (Green)";
		vehicleClass = "Air";
		transportSoldier = 3;
		ejectDamageLimit = 0.85;
		fuelCapacity = 500;
		transportMaxMagazines = 110;
		transportMaxWeapons = 30;
		transportMaxBackpacks = 10;
		cargoIsCoDriver[] = {1, 0};
		side = TCivilian;
		radartype = 0;
		crew = "RU_soldier";
		DriverAction = "Mi8_Pilot";
		cargoAction[] = {"V3S_Cargo01", "Truck_Cargo01", "Truck_Cargo01"};
		maxSpeed = 218;	// max speed on level road, km/h
		armor = 20;
		gearRetracting = false;
		cost = 500000;
		crewVulnerable = true;
		hasGunner = false;
		typicalCargo[] = {"Pilot"};
		weapons[] = {};
		magazines[] = {};
		supplyRadius = 2.5;
		type = VAir;
		enableManualFire = 0;
		viewCargoShadow = false;
		viewDriverShadow = false;
		
		class Turrets {};
		memoryPointsGetInDriver = "pos driver";
		memoryPointsGetInDriverDir = "pos driver dir";
		memoryPointsGetInCargo = "pos cargo";
		memoryPointsGetInCargoDir = "pos cargo dir";
		soundGetIn[] = {"ca\sounds\Air\Mi17\ext\ext-Mi17-getin-01", db0, 1};
		soundGetOut[] = {"ca\sounds\Air\Mi17\ext\ext-Mi17-getout-01", db0, 1, 50};
		soundDammage[] = {"ca\sounds\Air\Mi17\int\alarm_loop1", 0.001, 1};
		soundEngineOnInt[] = {"ca\sounds\Air\Mi17\int\int-Mi17-start-1a", 0.562341, 1.0};
		soundEngineOnExt[] = {"ca\sounds\Air\Mi17\ext\ext-Mi17-start-01a", 0.794328, 1.0, 800};
		soundEngineOffInt[] = {"ca\sounds\Air\Mi17\int\int-Mi17-stop-1a", 0.562341, 1.0};
		soundEngineOffExt[] = {"ca\sounds\Air\Mi17\ext\ext-Mi17-stop-01a", 0.794328, 1.0, 800};
		
		class Exhausts {
			class Exhaust1 {
				position = "vyfuk start";
				direction = "vyfuk end";
				effect = "ExhaustsEffectBig";
			};
		};
		
		class Sounds {
			class Engine {
				sound[] = {"ca\sounds\air\Mi17\ext\ext-sovietheli-engine-6", 5.62341, 1.0, 900};
				frequency = "rotorSpeed";
				volume = "camPos*((rotorSpeed-0.72)*4)";
			};
			
			class RotorLowOut {
				sound[] = {"ca\sounds\air\Mi17\ext\ext-Mi17-rotor-low-2", db5, 1.0, 1400};
				frequency = "rotorSpeed";
				volume = "camPos*(0 max (rotorSpeed-0.1))";
				cone[] = {1.6, 3.14, 2.0, 0.95};
			};
			
			class RotorHighOut {
				sound[] = {"ca\sounds\air\Mi17\ext\ext-Mi17-rotor-high-2", db10, 1.0, 1700};
				frequency = "rotorSpeed";
				volume = "camPos*10*(0 max (rotorThrust-0.9))";
				cone[] = {1.6, 3.14, 2.0, 0.95};
			};
			
			class EngineIn {
				sound[] = {"ca\sounds\air\Mi17\int\int-sovietheli-engine-3", db0, 1.0};
				frequency = "rotorSpeed";
				volume = "(1-camPos)*((rotorSpeed-0.75)*4)";
			};
			
			class RotorLowIn {
				sound[] = {"ca\sounds\air\Mi17\int\int-Mi17-rotor-low-2", db5, 1.0};
				frequency = "rotorSpeed";
				volume = "(1-camPos)*(0 max (rotorSpeed-0.1))";
			};
			
			class RotorHighIn {
				sound[] = {"ca\sounds\air\Mi17\int\int-Mi17-rotor-high-2", db5, 1.0};
				frequency = "rotorSpeed";
				volume = "(1-camPos)*3*(rotorThrust-0.9)";
			};
		};
		
		class Damage {
			tex[] = {"ca\wheeled2\v3s\data\v3s_kabpar_co.paa", "ca\wheeled2\v3s\data\v3s_kabpar_co.paa", "rth_copter\tex\damage_co.paa", "ca\misc\data\barel_06_co.paa", "ca\misc\data\barel_06_co.paa", "rth_copter\tex\damage_co.paa", "ca\misc\data\barel_05_co.paa", "ca\misc\data\barel_05_co.paa", "rth_copter\tex\damage_co.paa", "ca\misc\data\barel_02_co.paa", "ca\misc\data\barel_02_co.paa", "rth_copter\tex\damage_co.paa"};
			mat[] = {"ca\misc\data\detailmapy\barel.rvmat", "ca\misc\data\detailmapy\barel.rvmat", "rth_copter\tex\shader_destruct.rvmat", "ca\wheeled2\v3s\data\v3s_kabpar.rvmat", "ca\wheeled2\v3s\data\v3s_kabpar.rvmat", "ca\wheeled2\v3s\data\v3s_kabpar_destruct.rvmat"};
		};
		
		class Library {
			libTextDesc = "Homemade helicopter";
		};
	};
	
	class opragaCopter_yellow : pragaCopter_green {
		hiddenSelections[] = {"kabina"};
		hiddenSelectionsTextures[] = {"rth_copter\tex\v3s_kabpar_eciv_co.paa"};
		displayName = "Praga copter (Yellow)";
	};
};
